name: .NET

on:
  push:    { branches: [ master, dev ] }
  pull_request: { branches: [ master, dev ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: 8.0.x }
      - run: dotnet restore
      - run: dotnet build --no-restore

  test:
    needs: build
    runs-on: windows-latest        # ← run tests on Windows
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: 8.0.x }
      - run: dotnet test --no-build --verbosity normal
